=== xXxMONOxXx/SecondTask/src/main/resources/data/computerComponents.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns:xsi="http://www.w3.org/2001/XMLSchema"
        xsi:noNamespaceSchemaLocation="computerComponents.xsd">
    <complexType name="computer-component-type">
        <sequence>
            <element name="name">
                <simpleType>
                    <restriction base="string">
                        <minLength value="5"/>
                        <maxLength value="30"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="origin">
                <simpleType>
                    <restriction base="string">
                        <minLength value="2"/>
                        <maxLength value="30"/>
                    </restriction>
                </simpleType>
            </element>
            <element name="price" type="nonNegativeInteger"/>
            <element name="is-critical" type="boolean"/>
        </sequence>
        <attribute name="serial-number" type="ID" use="required"/>
        <attribute name="peripheral-type" type="peripheral-group" use="optional"/>
    </complexType>

    <complexType name="sound-type">
        <complexContent>
            <extension base="computer-component-type">
                <sequence>
                    <element name="port" type="port-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="mouse-type">
        <complexContent>
            <extension base="computer-component-type">
                <sequence>
                    <element name="port" type="port-type"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="keyboard-type">
        <complexContent>
            <extension base="computer-component-type">
                <sequence>
                    <element name="ports">
                        <complexType>
                            <sequence>
                                <element minOccurs="1" maxOccurs="unbounded" name="port" type="port-type"/>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="cpu-type">
        <complexContent>
            <extension base="computer-component-type">
                <sequence>
                    <element name="power-usage" type="nonNegativeInteger"/>
                    <element name="presence-of-fan" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="gpu-type">
        <complexContent>
            <extension base="computer-component-type">
                <sequence>
                    <element name="power-usage" type="nonNegativeInteger"/>
                    <element name="presence-of-fan" type="boolean"/>
                    <element name="ports">
                        <complexType>
                            <sequence>
                                <element minOccurs="1" maxOccurs="unbounded" name="port" type="port-type"/>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <element name="computer-component" type="computer-component-type" abstract="true"/>

    <element name="cpu" type="cpu-type" substitutionGroup="computer-component"/>

    <element name="headphones" type="sound-type" substitutionGroup="computer-component"/>

    <element name="mouse" type="mouse-type" substitutionGroup="computer-component"/>

    <element name="keyboard" type="keyboard-type" substitutionGroup="computer-component"/>

    <element name="gpu" type="gpu-type" substitutionGroup="computer-component"/>

    <element name="port-type">
        <simpleType>
            <restriction base="string">
                <enumeration value="USB"/>
                <enumeration value="COM"/>
                <enumeration value="LPT"/>
            </restriction>
        </simpleType>
    </element>

    <element name="peripheral-group">
        <simpleType>
            <restriction base="string">
                <enumeration value="multimedia"/>
                <enumeration value="io-device"/>
            </restriction>
        </simpleType>
    </element>

    <element name="devices">
        <complexType>
            <sequence>
                <element ref="computer-component" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
</schema>

=== xXxMONOxXx/SecondTask/src/main/resources/data/computerComponents.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="computerComponents.xsd">

    <cpu serial-number="1">
        <name>Intel</name>
        <origin>USA</origin>
        <price>499</price>
        <is-critical>true</is-critical>
        <power-usage>92</power-usage>
        <presence-of-fan>false</presence-of-fan>
    </cpu>

    <gpu serial-number="2">
        <name>Nvidia</name>
        <origin>USA</origin>
        <price>300</price>
        <is-critical>true</is-critical>
        <power-usage>150</power-usage>
        <presence-of-fan>true</presence-of-fan>
        <ports>
            <port>COM</port>
            <port>LPT</port>
        </ports>
    </gpu>

    <mouse serial-number="3" peripheral-type="io-device">
        <name>Razer</name>
        <origin>China</origin>
        <price>98</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </mouse>

    <headphones serial-number="4" peripheral-type="multimedia">
        <name>HyperX</name>
        <origin>China</origin>
        <price>120</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </headphones>

    <keyboard serial-number="5" peripheral-type="io-device">
        <name>SteelSeries</name>
        <origin>China</origin>
        <price>150</price>
        <is-critical>false</is-critical>
        <ports>
            <port>USB</port>
            <port>USB</port>
        </ports>
    </keyboard>

    <mouse serial-number="6" peripheral-type="io-device">
        <name>HeadPhones2</name>
        <origin>India</origin>
        <price>69</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </mouse>

    <headphones serial-number="7" peripheral-type="multimedia">
        <name>Mouse2</name>
        <origin>Russia</origin>
        <price>59</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </headphones>

    <keyboard serial-number="8" peripheral-type="io-device">
        <name>HyperX</name>
        <origin>China</origin>
        <price>200</price>
        <is-critical>true</is-critical>
        <ports>
            <port>USB</port>
        </ports>
    </keyboard>

    <keyboard serial-number="9" peripheral-type="io-device">
        <name>KeyBoard3</name>
        <origin>USA</origin>
        <price>280</price>
        <is-critical>true</is-critical>
        <ports>
            <port>USB</port>
            <port>USB</port>
            <port>USB</port>
        </ports>
    </keyboard>

    <cpu serial-number="10">
        <name>Elbrus</name>
        <origin>Russia</origin>
        <price>999</price>
        <is-critical>true</is-critical>
        <power-usage>192</power-usage>
        <presence-of-fan>true</presence-of-fan>
    </cpu>

    <gpu serial-number="11">
        <name>AMD</name>
        <origin>USA</origin>
        <price>400</price>
        <is-critical>true</is-critical>
        <power-usage>150</power-usage>
        <presence-of-fan>true</presence-of-fan>
        <ports>
            <port>COM</port>
            <port>COM</port>
            <port>COM</port>
        </ports>
    </gpu>

    <cpu serial-number="12">
        <name>AMD</name>
        <origin>USA</origin>
        <price>699</price>
        <is-critical>true</is-critical>
        <power-usage>102</power-usage>
        <presence-of-fan>true</presence-of-fan>
    </cpu>

    <gpu serial-number="13">
        <name>Nvidia</name>
        <origin>USA</origin>
        <price>350</price>
        <is-critical>true</is-critical>
        <power-usage>160</power-usage>
        <presence-of-fan>true</presence-of-fan>
        <ports>
            <port>COM</port>
            <port>LPT</port>
        </ports>
    </gpu>

    <headphones serial-number="14" peripheral-type="multimedia">
        <name>Bloody</name>
        <origin>China</origin>
        <price>89</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </headphones>

    <keyboard serial-number="15" peripheral-type="io-device">
        <name>Bloody</name>
        <origin>China</origin>
        <price>79</price>
        <is-critical>true</is-critical>
        <ports>
            <port>USB</port>
        </ports>
    </keyboard>

    <mouse serial-number="16" peripheral-type="io-device">
        <name>Bloody</name>
        <origin>China</origin>
        <price>60</price>
        <is-critical>false</is-critical>
        <port>USB</port>
    </mouse>

</devices>
